spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: DataEngineeringIsCool2023
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351